apiVersion: v1
kind: ResourceQuota
metadata:
  name: aviz-demo
  namespace: aviz-demo
spec:
  hard:
    # Pod count cap
    pods: "10"
    # CPU: sum of all pod requests / limits in this namespace
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1500m"
    limits.memory: "1Gi"
    # Service caps
    services.loadbalancers: "1"
    services.nodeports: "0"
